# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: zoomcamp
channels:
  - conda-forge
dependencies:
  - python >=3.10,<3.11
  - ipykernel
  - ipywidgets
  - numpy
  - pandas
  - kaggle
  - scikit-learn==1.3.1
  - scikit-learn-intelex
  - matplotlib==3.7
  - seaborn
  - plotly
  - regex
  - tqdm
  - nbformat
  - ydata-profiling

